apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: chatapp-backend-pod
        image: rvarshney6168/chatapp-backend
        ports:
        - containerPort: 5001
        env:
         - name: NODE_ENV
           value: Production
         - name: MONGODB_URI
           value: "mongodb://mongoadmin:secret@mongodb:27017/dbname?authSource=admin"
         - name: JWT_SECRET
           valueFrom:
             secretKeyRef:
              name: chatapp-secrets
              key: jwt 
         - name: PORT
           value: "5001"
