apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: chat-app
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/mongo-data


